[package]
name = "visual"
version = "0.0.1"
description = "VisualCraft - 可视化工匠 - A powerful visualization and editing tool"
authors = ["Joel Xiao"]
license = ""
repository = ""
default-run = "visual"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.5.2", features = [] }

[dependencies]
tauri = { version = "2.9.3", features = [] }
